In [ ]:
import numpy as np

array creation

In [ ]:
arr=np.array([10,20,30])
arr

array([10, 20, 30])

array creation with set

In [ ]:
arr=np.array({10,20,30})
arr

array({10, 20, 30}, dtype=object)

array creation with different DAtaTypes

In [ ]:
arr=np.array([10+8j,20,'30',{10,20}])
arr

array([(10+8j), 20, '30', {10, 20}], dtype=object)

In [ ]:
arr=np.array([10,20.,30])
arr

array([10., 20., 30.])

In [ ]:
arr_2d=np.array([[10,20,30],
                 [40,50,40]])
arr_2d

array([[10, 20, 30],
       [40, 50, 40]])

In [ ]:
arr_3d=np.array([[[10,20,30],[40,50,60],[23,34,56]],
                 [[100,200,300],[400,500,600],[23,45,67]]])
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 23,  34,  56]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

In [ ]:
arr.ndim
arr_3d.ndim

3

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 23,  34,  56]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

In [ ]:
arr_3d.size

18

In [ ]:
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 23,  34,  56]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

In [ ]:
arr.shape
arr_2d.shape
arr_3d.shape

(2, 3, 3)

In [ ]:
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 23,  34,  56]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

In [ ]:
arr_3d.shape

(2, 3, 3)

In [ ]:
arr=np.array([10,20,30,40,50,60])

In [ ]:
arr

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr.reshape(1,3,2)

array([[[10, 20],
        [30, 40],
        [50, 60]]])

In [ ]:
arr.reshape(1,2,3)

array([[[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
arr.reshape(2,3,1)

array([[[10],
        [20],
        [30]],

       [[40],
        [50],
        [60]]])

In [ ]:
arr.reshape(3,1,2)

array([[[10, 20]],

       [[30, 40]],

       [[50, 60]]])

In [ ]:
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 23,  34,  56]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

In [ ]:
arr_3d.reshape(-1)

array([ 10,  20,  30,  40,  50,  60,  23,  34,  56, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

In [ ]:
arr_3d.flatten()

array([ 10,  20,  30,  40,  50,  60,  23,  34,  56, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

In [ ]:
arr_3d.ravel()

array([ 10,  20,  30,  40,  50,  60,  23,  34,  56, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

In [ ]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
a=np.linspace(1,100,3000)

In [ ]:
np.zeros((2,3,6),dtype=int)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [ ]:
np.ones((4,9),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((5,7))

array([[7.08140580e-316, 0.00000000e+000, 6.68487724e-310,
        6.68488514e-310, 5.78342968e-317, 5.78345340e-317,
        6.68487115e-310],
       [6.68487115e-310, 6.68488370e-310, 6.68487115e-310,
        7.62201633e-316, 6.68487115e-310, 6.68488538e-310,
        6.68487127e-310],
       [6.68487127e-310, 6.68487115e-310, 6.68487115e-310,
        6.68487815e-310, 6.68487126e-310, 6.68487126e-310,
        6.68487126e-310],
       [5.36444621e-317, 6.68488321e-310, 6.68487121e-310,
        6.68488518e-310, 6.68487126e-310, 6.68487115e-310,
        6.68487815e-310],
       [6.68487115e-310, 6.68488370e-310, 6.68488513e-310,
        6.68487115e-310, 6.68487115e-310, 6.68487118e-310,
        2.05531309e-321]])

In [ ]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

array manipulation


In [ ]:
arr

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr.astype(dtype=float)

array([10., 20., 30., 40., 50., 60.])

In [ ]:
arr=np.arange(1,11)
arr2=np.arange(11,21)
print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
new_arr=np.concatenate((arr,arr2))
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr=np.arange(1,5)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
np.repeat(arr,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [ ]:
arr1=np.full((5,5),(1,2,3,4,5))
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
a=arr1.T
a

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
np.flip(arr1)

array([[5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1]])

In [ ]:
arr=np.array([12,34,21,36,78,32,12,21,67,89])
arr

array([12, 34, 21, 36, 78, 32, 12, 21, 67, 89])

In [ ]:
np.unique(arr)

array([12, 21, 32, 34, 36, 67, 78, 89])

In [ ]:
arr

array([12, 34, 21, 36, 78, 32, 12, 21, 67, 89])

In [ ]:
a=np.split(arr,5)
a

[array([12, 34]),
 array([21, 36]),
 array([78, 32]),
 array([12, 21]),
 array([67, 89])]

In [ ]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
arr2=np.array([4,5,689])

In [ ]:
np.vstack((arr,arr1,arr2))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  4,   5, 689]])

In [ ]:
a=np.hstack((arr,arr1,arr2))

In [ ]:
a

array([  1,   2,   3,   4,   5,   6,   4,   5, 689])

In [ ]:
b=np.delete(a,4)

In [ ]:
a

array([  1,   2,   3,   4,   5,   6,   4,   5, 689])

In [ ]:
a=[10,20,30]
b=a
b[2]=300
print(a)
print(b)

[10, 20, 300]
[10, 20, 300]


In [ ]:
a=[10,20,30]
b=a.copy()
b[2]=300
print(a)
print(b)

[10, 20, 30]
[10, 20, 300]


In [ ]:
import copy
a=[10,20,30,40,[10,20,30]]
b=copy.deepcopy(a)
b[2]=300
b[-1][-1]=300
print(a)
print(b)

[10, 20, 30, 40, [10, 20, 30]]
[10, 20, 300, 40, [10, 20, 300]]


In [ ]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
c=arr.copy()

In [ ]:
id(c)

135303294348496

In [ ]:
c[3]=40

In [ ]:
c

array([ 0,  2,  4, 40,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr_2d=np.arange(0,20).reshape(5,4)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
d=arr_2d.copy()

In [ ]:
d[4][2]=800

In [ ]:
d

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17, 800,  19]])

In [ ]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a=arr.view()

In [ ]:
a[3]=300

In [ ]:
arr

array([  0,   2,   4, 300,   8,  10,  12,  14,  16,  18,  20])

In [ ]:
a

array([  0,   2,   4, 300,   8,  10,  12,  14,  16,  18,  20])

In [ ]:
e=arr_2d.view()

In [ ]:
e[4][2]=340

In [ ]:
e

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17, 340,  19]])

In [ ]:
arr_2d

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17, 340,  19]])

### 🧩 **1\. Data Entry System**

A data analyst needs to store the ages of employees: 25, 28, 32, 45, and 50.She wants to create a structure that supports mathematical operations like finding the mean or sum easily.

🔹 Create a suitable structure and display its number of dimensions and total elements.


In [ ]:
ages=np.array([25,28,32,45,50])
print(ages)
print(ages.ndim)
print(ages.size)

[25 28 32 45 50]
1
5


### 🔢 **2\. Temperature Readings**

You are asked to record hourly temperature readings from **6 AM to 6 PM (12 readings)**, starting from 6 and increasing by 1 hour each time.

🔹 Create an array that represents these time intervals.

🔹 Reshape it into a 3×4 matrix to represent readings of **3 days**.

🔹 Display its shape and transpose it.

In [ ]:
time=np.arange(6,18)
reshaped_time=time.reshape(3,4)

In [ ]:
reshaped_time.shape

(3, 4)

In [ ]:
reshaped_time.T

array([[ 6, 10, 14],
       [ 7, 11, 15],
       [ 8, 12, 16],
       [ 9, 13, 17]])

### 🧮 **3\. Image Matrix Setup**

A machine learning engineer is initializing a 5×5 grayscale image matrix where each pixel starts with value 0.Later, she wants to change the center pixel’s value to 255.

🔹 Create and display the initial matrix.

🔹 Modify the center pixel value.





In [ ]:
img_mtx=np.zeros((5,5))
img_mtx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ⚙️ **4\. Product Code Generator**

A company wants to assign product codes starting from **1000 to 1990** at equal intervals (10 products per step).

🔹 Create an array of all product codes.

🔹 Display only the first and last five codes.

🔹 Find how many total product codes are generated.

In [ ]:
prod_code=np.arange(1000,1991,10)
prod_code

array([1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100,
       1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210,
       1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320,
       1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430,
       1440, 1450, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540,
       1550, 1560, 1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650,
       1660, 1670, 1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750, 1760,
       1770, 1780, 1790, 1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870,
       1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980,
       1990])

In [ ]:
prod_code.size

100

### 🧠 **5\. Custom Matrix Challenge**

A scientist needs a **4×4 matrix** where all cells initially contain the value **7**,but she also wants an **identity pattern** (1s on the main diagonal).

🔹 Create both arrays.

🔹 Replace the diagonal of the first array with the diagonal of the second.

🔹 Display the final matrix.

In [ ]:
sev_mtx=np.full((4,4),7)

In [ ]:
ident=np.identity(4,dtype=int)

In [ ]:
print(sev_mtx)
print(ident)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# for i in range(4):
#     sev_mtx[i,i]=ident[i,i]
# sev_mtx

array([[1, 7, 7, 7],
       [7, 1, 7, 7],
       [7, 7, 1, 7],
       [7, 7, 7, 1]])

In [ ]:
# a=np.array([1,2,3])
np.fill_diagonal(sev_mtx,[1,2,3])

In [ ]:
sev_mtx

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 1]])

### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

# 📚 Student Marks Management System - NumPy Tutorial

[![Python](https://img.shields.io/badge/Python-3.6%2B-blue.svg)](https://www.python.org/)
[![NumPy](https://img.shields.io/badge/NumPy-1.19%2B-orange.svg)](https://numpy.org/)
[![Jupyter](https://img.shields.io/badge/Jupyter-Notebook-F37626.svg)](https://jupyter.org/)

A comprehensive interactive Jupyter notebook demonstrating NumPy fundamentals through a practical student marks management system. This educational project covers array operations, statistical analysis, and data manipulation using real-world scenarios.

## 🎯 Project Overview

This interactive notebook serves as a hands-on tutorial for learning NumPy by building a student marks management system. It covers essential NumPy concepts including array creation, manipulation, statistical operations, and practical data analysis with live code execution and visualizations.

## ✨ Features

### Module 1: Array Basics & Properties
- Creating NumPy arrays from Python lists
- Understanding array properties (shape, size, dtype, ndim)
- Comparing NumPy arrays with Python lists

### Module 2: Array Creation Functions
- **Range-based Creation**: `arange()`, `linspace()`
- **Initialized Arrays**: `zeros()`, `ones()`, `empty()`, `full()`
- **Special Matrices**: `identity()`, `eye()`

### Module 3: Array Manipulation
- **Shape Operations**: `reshape()`, `flatten()`, `ravel()`, `transpose()`
- **Combining Arrays**: `concatenate()`, `vstack()`, `hstack()`, `hsplit()`
- **Modification**: `repeat()`, `flip()`, `delete()`, `unique()`
- **Type Conversion**: `astype()`, `copy()`, `view()`

### Practical Application
- Statistical analysis (mean, sum, max, min, std)
- Student performance tracking
- Subject-wise analysis
- Top performer identification

## 🚀 Getting Started

### Prerequisites

```bash
Python 3.6+
Jupyter Notebook or JupyterLab
NumPy library
```

### Installation

1. Clone the repository:
```bash
git clone https://github.com/yourusername/numpy-student-marks-management.git
cd numpy-student-marks-management
```

2. Install dependencies:
```bash
pip install numpy jupyter
```

### Running the Notebook

**Option 1: Jupyter Notebook**
```bash
jupyter notebook student_marks_system.ipynb
```

**Option 2: JupyterLab**
```bash
jupyter lab student_marks_system.ipynb
```

**Option 3: Google Colab**
1. Upload the `.ipynb` file to Google Drive
2. Open with Google Colab
3. Run all cells (Runtime → Run all)

**Option 4: VS Code**
1. Install Python and Jupyter extensions
2. Open the `.ipynb` file
3. Select Python kernel and run cells

## 📊 Sample Output

The notebook analyzes marks for 6 students across 4 subjects:
- **Students**: Alice, Bob, Charlie, Diana, Eve, Frank
- **Subjects**: Math, Physics, Chemistry, Biology

**Example Analysis:**
```
Average marks per student: [85.75 70.5  91.25 68.75 87.5  79.  ]
Top performing student: Charlie
Average score: 91.25

Subject with highest average: Math
Average score: 80.67
```

## 📖 Learning Objectives

After working through this notebook, you will understand:

1. **NumPy Array Fundamentals**
   - Array creation and initialization
   - Array properties and attributes
   - Memory efficiency compared to Python lists

2. **Array Operations**
   - Shape manipulation and transformations
   - Combining and splitting arrays
   - Element-wise operations

3. **Statistical Analysis**
   - Aggregation functions (mean, sum, std)
   - Axis-based operations
   - Finding maximum/minimum values

4. **Practical Applications**
   - Real-world data manipulation
   - Performance analysis
   - Data transformation techniques

## 🔧 Key NumPy Functions Demonstrated

| Category | Functions |
|----------|-----------|
| Creation | `array()`, `arange()`, `linspace()`, `zeros()`, `ones()`, `full()`, `empty()` |
| Shape | `reshape()`, `flatten()`, `ravel()`, `transpose()` |
| Combining | `concatenate()`, `vstack()`, `hstack()`, `hsplit()` |
| Statistics | `mean()`, `sum()`, `max()`, `min()`, `std()`, `argmax()` |
| Manipulation | `repeat()`, `flip()`, `delete()`, `unique()`, `astype()` |

## 📁 Project Structure

```
numpy-student-marks-management/
│
├── student_marks_system.ipynb    # Main Jupyter notebook
├── README.md                      # Project documentation
├── requirements.txt               # Python dependencies
└── LICENSE                        # License file
```

## 💡 Use Cases

This notebook structure can be adapted for:
- Academic grade management systems
- Sports statistics tracking
- Sales performance analysis
- Scientific data processing
- Financial data analysis
- Educational tutorials and workshops

## 🎓 How to Use This Notebook

1. **Sequential Learning**: Run cells in order from top to bottom
2. **Interactive Exploration**: Modify values and re-run cells to see different results
3. **Experimentation**: Add new cells to test your own NumPy operations
4. **Documentation**: Each section is well-documented with explanations
5. **Practice**: Try changing student names, marks, or adding more subjects

## 🤝 Contributing

Contributions are welcome! Feel free to:
- Add data visualizations (matplotlib, seaborn)
- Include more statistical analyses
- Add interactive widgets (ipywidgets)
- Improve documentation and examples
- Report bugs or issues
- Suggest additional NumPy functions to demonstrate

### How to Contribute
1. Fork the repository
2. Create your feature branch (`git checkout -b feature/AmazingFeature`)
3. Commit your changes (`git commit -m 'Add some AmazingFeature'`)
4. Push to the branch (`git push origin feature/AmazingFeature`)
5. Open a Pull Request

## 📝 License

This project is licensed under the MIT License - see the LICENSE file for details.

## 👨‍💻 Author

Your Name
- GitHub: [@yourusername](https://github.com/yourusername)
- LinkedIn: [Your LinkedIn](https://linkedin.com/in/yourprofile)
- Email: your.email@example.com

## 🙏 Acknowledgments

- NumPy documentation and community
- Jupyter Project for the amazing notebook interface
- Educational resources on array programming
- Open source contributors

## 📚 Additional Resources

- [NumPy Official Documentation](https://numpy.org/doc/)
- [Jupyter Notebook Documentation](https://jupyter-notebook.readthedocs.io/)
- [NumPy Tutorial for Beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)

## 🐛 Troubleshooting

**Kernel Issues:**
- Restart kernel: `Kernel → Restart & Clear Output`
- Reinstall NumPy: `pip install --upgrade numpy`

**Import Errors:**
- Ensure NumPy is installed: `pip install numpy`
- Check Python version compatibility

**Cell Not Running:**
- Check if another cell is currently executing
- Restart the kernel and run again

---

⭐ **If you find this notebook helpful, please consider giving it a star!**

📧 **Questions or suggestions?** Open an issue or reach out!

**Happy Learning! 🎓**